apiVersion: apps/v1
kind: Deployment
metadata:
  name: vimal-hello
  labels:
    app: hello-world1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world1
  template:
    metadata:
      labels:
        app: hello-world1
    spec:
      containers:
      - name: vimal-kubecon
        image: vimalpadmanathan/vimalhelloworld:v1
        ports:
        - containerPort: 80			
