apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vimal-service
            port:
              number: 80
